//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigInterp.Sql
{
    using System;
    
    public partial class GetActionParmDescAndValidationInfoResult
    {
        public string ParamDesc { get; set; }
        public int ValueTypeId { get; set; }
        public short OrderSequence { get; set; }
        public int FormatTypeId { get; set; }
        public string FormatDesc { get; set; }
        public string FormatInputPattern { get; set; }
        public string FormatInputHintDesc { get; set; }
        public short MinSize { get; set; }
        public short MaxSize { get; set; }
        public bool IsOptional { get; set; }
        public string ParamPseudoDesc { get; set; }
    }
}
