//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigInterp.Sql
{
    using System;
    
    public partial class GetBenefitMatrixNarrativeVersionResult
    {
        public string FieldId { get; set; }
        public string DescriptionKey { get; set; }
    }
}
