//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigInterp.Sql
{
    using System;
    
    public partial class GetCompareTypeDescResult
    {
        public int CompareTypeId { get; set; }
        public string CompareTypeDesc { get; set; }
        public string CompareTypePseudoDesc { get; set; }
    }
}
