//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigInterp.Sql
{
    using System;
    
    public partial class GetFieldNameDescResult
    {
        public long FieldId { get; set; }
        public string FieldDesc { get; set; }
        public string FieldPseudoDesc { get; set; }
        public string QualifierPseudoDesc { get; set; }
    }
}
