var autoComplete = function () {
    $("select").searchable({
        maxListSize: 100,						// if list size are less than maxListSize, show them all
        maxMultiMatch: 50,						// how many matching entries should be displayed
        exactMatch: false,						// Exact matching on search
        wildcards: true,						// Support for wildcard characters (*, ?)
        ignoreCase: true,						// Ignore case sensitivity
        latency: 200,							// how many millis to wait until starting search
        warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch
        warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
        zIndex: 'auto'							// zIndex for elements generated by this plugin
    });
};

var saveNewInterp = function () {
    var _data = typeof $("#InterpId").val() === 'string' ? $("#InterpId").val() : '';

    $("#openInterpSpinner").removeClass("hidden");

    var options = {
        url: $("#dvSitePath").html() + 'Interp/SaveNewInterp',
        form: 'get',
        data: _data
    };
    $("#imgNewInterp").attr("src", "");
    $.ajax(options).done(function (data) {

        newInterpbuttonStateChange(data);
        if (data.ViewInterp === 1) {
            showToast.success("Interp saved successfully");
            $("#InterpId").removeClass("InvalidField");
            $("#imgNewInterp").attr("src", $("#dvSitePath").html() + "/Images/success.png");
        }
    });
    var url = $("#dvSitePath").html() + 'Interp/EditInterp?InterpQueryId=' + $("#InterpId").val();

    clearNewInterp();

    $.get(url)
   .done(
       function () {
           document.location = url;
           $("#openInterpSpinner").addClass("hidden");
       })
   .fail(
       function () {
           alert("Error: Invalid Interp Number");
           $("#openInterpSpinner").addClass("hidden");
           $("#btnOpenInterp").removeClass("hidden");
           $("#createInterpModalButton").removeClass("hidden");
       });
};


var openInterpInView = function () {
    $("#frmViewInterp").submit();
};

var clearNewInterp = function () {
    $("#InterpId").val('');
    $("#imgNewInterp").attr("src", "");
    $("#InterpMessage").html('');
    $("#dvOutline").html('');
    $("#dvCategory").html('');
    $("#dvSubCategory").html('');
    $("#dvInterpId").html('');
    $("#dvNewInterpLevel").html('');
    $("#InterpId").removeClass("InvalidField");
};

var newInterpControlsSetup = function () {

    $("#InterpNumber").mask("99-999-999-9999", { placeholder: "##-###-###-####" });

    $("#InterpId").mask("99-999-999-9999", { placeholder: "##-###-###-####" });

    $("#btnCancelNewIntrep").click(clearNewInterp);

    $("#btnCreateNewIntrep").prop("disabled", true);

    $("#InterpNumber").on('input keyup copy paste cut', validOpenInterp);

    $("#InterpId").on('input keyup copy paste cut', querySubmitNewInterp);

    $("#btnCreateNewIntrep").click(saveNewInterp);

    $("#ViewInterpLink").click(openInterpInView);

    $("#createInterpModalButton").click(querySubmitNewInterp);

};

var validOpenInterp = function () {
    var currentInterpNumber = $("#InterpNumber").val();
    var interpId = typeof currentInterpNumber === 'string' ? currentInterpNumber : '';

    interpId = interpId.replace(/#/g, '');
    interpId = interpId.replace(/-/g, '');

    if (interpId.length === 12) {
        $('#btnOpenInterp').prop('disabled', false);
        // set Create New Interp input to Open Interp value
        $("#InterpId").val(currentInterpNumber);
    } else {
        $('#btnOpenInterp').prop('disabled', true);
    }

};

var querySubmitNewInterp = function () {

    var _data = typeof $("#InterpId").val() === 'string' ? $("#InterpId").val() : '';

    var interpId = _data.replace(/#/g, '');
    interpId = interpId.replace(/-/g, '');

    if (interpId.length === 0) {
        $("#dvOutline").html('');
        $("#dvCategory").html("");
        $("#dvSubCategory").html("");
        $("#dvInterpId").html("");
        $("#dvNewInterpLevel").html("");
        $("#imgNewInterp").attr("src", "");
        $("#InterpMessage").html("");
        $("#InterpId").removeClass("InvalidField");
    } else if (interpId.length === 2 || interpId.length === 5 || interpId.length === 8 || interpId.length === 12) {
        var options = {
            url: $("#dvSitePath").html() + '/Interp/InterpSections',
            type: 'GET',
            cache: false,
            data: _data
        };

        $("#imgNewInterp").attr("src", $("#dvSitePath").html() + "/Images/linear_loading.gif");
        $("#imgNewInterp").addClass("Spinner");
        $("#InterpMessage").html("");

        $.ajaxSetup({ cache: false });
        $.ajax(options).done(function (data) {

            $("#imgNewInterp").attr("src", "");

            if (String(data.InterpEror) === "Yes") {
                $("#InterpId").addClass("InvalidField");
                $("#InterpMessage").html(data.InterpErrorText);
                $("#btnCreateNewIntrep").prop("disabled", true);
                $("#imgNewInterp").attr("src", $("#dvSitePath").html() + "Images/invalid@2X.png");
            }
            else {
                $("#InterpId").removeClass("InvalidField");
                $("#InterpMessage").html('');
            }

            if (String(data.Outline_Description).length > 0) {
                $("#dvOutline").html(String(data.Outline_Number) + " - " + String(data.Outline_Description));
            }
            else {
                $("#dvOutline").html('');
            }
            if (String(data.Category_Description).length > 0) {
                $("#dvCategory").html(String(data.Category_Number) + " - " + String(data.Category_Description));
            }
            else {
                $("#dvCategory").html("");
            }
            if (String(data.SubCategory_Description).length > 0) {
                $("#dvSubCategory").html(String(data.SubCategory_Number) + " - " + data.SubCategory_Description);
            }
            else {
                $("#dvSubCategory").html("");
            }
            if (String(data.InterpId_Number).length > 0) {
                $("#dvInterpId").html(String(data.InterpId_Number));

                if (String(data.InterpEror) === "No") {
                    $("#btnCreateNewIntrep").prop("disabled", false);
                }
            }
            else {
                $("#dvInterpId").html("");
            }

            if (String(data.Level_Description).length > 0) {
                $("#dvNewInterpLevel").html(String(data.Level_Description));
            } else {
                $("#dvNewInterpLevel").html("");
            }
            if (String(data.InterpEror) === "No") {
                newInterpbuttonStateChange(data);
            }
            else {
                $("#imgNewInterp").attr("src", $("#dvSitePath").html() + "Images/invalid.png");
            }

            if (data.ViewInterp === 1) {
                $("#imgNewInterp").attr("src", $("#dvSitePath").html() + "Images/invalid.png");
            }

        });
    }
};

var newInterpbuttonStateChange = function (data) {

    if (data.CreateNewInterp === 1) {
        $("#btnCreateNewIntrep").prop("disabled", false);
        $("#imgNewInterp").attr("src", $("#dvSitePath").html() + "Images/success.png");
        $("#InterpMessage").text(data.InterpMessage.trim());
    }
    else {
        $("#btnCreateNewIntrep").prop("disabled", true);
    }

    if (data.CreateNewInterp === 0) {
        if (data.ViewInterp === 1) {
            $("#InterpMessage").text(data.InterpMessage.trim());
            $("#InterpId").addClass("InvalidField");
        }
        else {
            $("#ViewInterpLink").removeClass("show").addClass("hidden");
            $("#InterpId").removeClass("InvalidField");
            $("#InterpMessage").text("");
        }
    }

};

var openInterpButton = function () {
    var interpIds = typeof $("#InterpNumber").val() === 'string' ? $("#InterpNumber").val() : '';


    var interpIdTemp = interpIds.replace(/#/g, '');
    interpIdTemp = interpIdTemp.replace(/-/g, '');

    if (interpIds.length === 12) {
        $('#btnOpenInterp').prop('disabled', false);
    }

    $('#lnkInterpConfiguratorHome').attr("href", $("#dvSitePath").html() + 'Interp/Index');

    //$('#lnkInterpConfiguratorHome').click(function () {
    //    document.location = $("#dvSitePath").html() + 'Interp/Index';
    //});

    $('#btnOpenInterp').click(function () {
        var url = $("#dvSitePath").html() + 'Interp/ViewInterp?InterpQueryId=' + $("#InterpNumber").val();

        $("#openInterpSpinner").removeClass("hidden");
        $("#btnOpenInterp").addClass("hidden");
        $("#createInterpModalButton").addClass("hidden");

        $.get(url)
        .done(
            function () {
                document.location = url;
                $("#openInterpSpinner").addClass("hidden");
            })
        .fail(
            function () {
                alert("Error: Invalid Interp Number");
                $("#openInterpSpinner").addClass("hidden");
                $("#btnOpenInterp").removeClass("hidden");
                $("#createInterpModalButton").removeClass("hidden");
            });

    });

};

var newInterpFunctionCall = function () {
    autoComplete();
    openInterpButton();
    newInterpControlsSetup();
};

